---
- src: https://github.com/ProfessionalTiger/Terraforms/blob/master/ansible-role
  version: master
  name: ansible-role
- name: Test
  hosts: all
  gather_facts: false
  become: true
  connection: local
  tasks:
    - import_role:
       name: terraform
