---
- name: plan
  terraform:
    project_path: '/usr/local/bin/'
    plan_file: 'tfplan'
    lock: true
    state: planned

- name: apply
  terraform:
    project_path: '/usr/local/bin/'
    lock: true
    state: present

- name: destroy
  terraform:
    project_path: '/usr/local/bin/'
    lock: false
    state: absent
